#!/bin/bash

# Quick demo script for Paros weather Slack integration

echo "🌤️  Paros Weather Slack Bot - Quick Demo"
echo "========================================"
echo ""
echo "This weather service includes automatic Paros weather responses!"
echo ""
echo "How it works:"
echo "  1. Someone mentions 'paros' in any Slack channel (case-insensitive)"
echo "  2. The bot automatically fetches current Paros weather"
echo "  3. Responds in Norwegian with temperature, conditions, and wind"
echo ""
echo "Example response:"
echo '  "På Paros er det no 22.5 grader og Sunny, vinden er 3.2 m/s, retning NW"'
echo ""
echo "Setup Requirements:"
echo "  ✓ WeatherAPI.com API key (for weather data)"
echo "  ✓ Slack Bot Token (to send messages)"
echo "  ✓ Slack App ID (prevents duplicate messages)"
echo "  ✓ Bot subscribed to message.channels event"
echo "  ✓ Bot invited to Slack channels"
echo ""
echo "Quick Start:"
echo "  1. export WEATHERAPI_KEY=your_key"
echo "  2. export SLACK_BOT_TOKEN=xoxb-your-token"
echo "  3. export SLACK_APP_ID=A01234567"
echo "  4. ./build/weather_service -s -p 8080 -v"
echo "  5. Configure Slack app to point to your server"
echo "  6. Invite bot to a channel"
echo "  7. Mention 'paros' in a message"
echo ""
echo "For detailed setup, see SLACK.md"
echo "========================================"
