apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
stringData:
  token: eyJhIjoiYmRjZTVmNDhjNmE2YTA0MzI3MGYxOTBmN2U5NGRiN2YiLCJ0IjoiNDdmNWE2YjEtY2M4MS00NTc4LWI1MTQtODYzMmI2NjQxZDYwIiwicyI6Ik1HUXdPVGMxTVRNdE1qWXpOaTAwTVRWaUxXRTJORGN0TVRFNE9UWTVOalF3WWpNeCJ9
